### ISSUE TITLE
Angular 4 compatibility?

### ISSUE THREAD

**Issue by klihelp** [shlomiassaf/ngc-webpack#13]
Please make project compatible to the latest Angular (version 4)

**Comment by shlomiassaf** [comment]
@klihelp I will post a new version of the project in the upcoming hour.

I did not have any issues with angular 4 compilation, can you elaborate?

Is it just a package dependency reference issue?

**Comment by klihelp** [comment]
yes. and check for latest packages not just for angular 4
`npm outdated`

**Comment by evanjmg** [comment]
It works fine for angular 4 here.
