### ISSUE TITLE
ngc-webpack with `webpack.config.ts` does not work well

### ISSUE THREAD

**Issue by watiko** [shlomiassaf/ngc-webpack#19]
# Problem
When I build my project with `webpack.config.ts` which imports `ngc-webpack`, I got the following error:

```
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
config\helpers.ts (10,25): Parameter 'flag' implicitly has an 'any' type. (7006)
```

Of course `config/helpers.ts` is fully typed and the project had built successfully before I have updated dependencies. 

# Investigation
I realized that `ts-node` should be loaded only once. (source: https://github.com/TypeStrong/ts-node/issues/333#issuecomment-301861566)

- [This commit](https://github.com/shlomiassaf/ngc-webpack/commit/968811bff8ff91b4ba5be7010183e53c1461b323) introduces `require('ts-node/register')` into `ngc-webpack` itself.
- `webpack` register `ts-node` automatically in detecting `webpack.config.ts`. (source: https://github.com/webpack/webpack/blob/v2.6.1/bin/convert-argv.js)

So my project register `ts-node` twice...

**Comment by shlomiassaf** [comment]
This should be fixed in 3.0.0
