### ISSUE TITLE
@ngtools/webpack

### ISSUE THREAD

**Issue by fxck** [shlomiassaf/ngc-webpack#2]
I take it this is basically a temporary replacement solution for `AotPlugin`, right? Now, do people at `@angular/angular-cli` know of the problems people encounter using `AotPlugin`, or in other words, are there issues open for the problems this plugin solves? 

Basically I very much agree with..

> In the future I hope we all converge into 1 solution, `@ngtools/webpack`

..and while this plugin is a great replacement, I would love to be able to a) track the issues so I know when it's safe to switch b) make sure that `@angular/angular-cli` members are aware of the problems..

**Comment by shlomiassaf** [comment]
@fxck You are more then welcome to:

a) find the issues (if any) you have with the AotPlugin and log theme here.
b) Contact the angular-cli team and make them aware of this.

Both a & b does not require anything other then time.

I built this solution since I couldn't find something to solve my problems. 
I'v contributed to the angular project, I know the process to promote a change/proposal from the outside, it takes time...

Normally I would give it a shot but this time I couldn't spare the time, instead I decided to share it and spend some time documenting it. 

So here you are, raising an issue lets see you do something about it... otherwise this is just complaining... maybe thinking I own something to someone... common :)

**Comment by shlomiassaf** [comment]
BTW, the need I had to provide solid AOT build also led to `ng-router-loader` and to the AngularClass starter to have a solid and complete AOT build...

Same thing goes to creating a new lib to replace `angular-router-loader`... yes I could have asked the owner to makes changes... the amount of time it would have taken me to explain the issues and make him agree (which is not certain) equals ages for me.

It just wasn't real to wait

**Comment by fxck** [comment]
Come on.. I didn't mean to neither complain nor offend you. I personally didn't really have any problems with `AotPlugin`, other than with invludePaths not working.

> I built this solution since I couldn't find something to solve my problems.

...this is pretty much what I was asking for, whether you created issues for those problems, if not I can try and open them, but without knowing what they are, I can't be much of a help.

**Comment by shlomiassaf** [comment]
Its hard for me to say as I didn't use AOTPlugin for quite some time...

Mainly,

 - I want to select my own TS loader, this is a huge deal breaker for many reasons.
 - I want to be able to control the resources before the compiler processes them.

The 2nd allows me to:
 a) replace styles/templates which allows for example restyling material
 b) replace component templates with empty content to reduce bundle size (AOTPlugin might do that I don't know...)

Anyway, **IMO**,  it's not a good design to abstract TS compilation from the developer.
It ends up creating a bottle neck for TS version support... 

The current implementation preforms an in-memory compilation and manipulates the webpack dependency tree so those in-memory files (ngfactory) are added as virtual files.

My implementation first emits the files to the file system then bundle them up.
It might be slower, but it's more native and doesn't require special logic in the plugin but running the compiler-cli.  
One more issue is that it doesn't support watch for AOT, I don't know if AOTPlugin supports that mine does not.

All in all, the AOTPlugin is super complex, this plugin is super simple and does not couple anything 

If I can use my own TS loader, hook into resources and sorts then I would move :)

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
