### ISSUE TITLE
Code for v3?

### ISSUE THREAD

**Issue by BendingBender** [shlomiassaf/ngc-webpack#20]
I have an issue with v3 of ngc-webpack and wanted to make a pull request. Now I can't find the code for v3 anywhere in this repo. The v3 npm package links to this repo and I can't find any other similar repo neither on google nor on github. Would you mind to push the code here or post a link to the new repo?

**Comment by shlomiassaf** [comment]
my bad, pushed it now

**Comment by BendingBender** [comment]
Thanks!
