### ISSUE TITLE
ngc-webpack Aot

### ISSUE THREAD

**Issue by abadakhshan** [shlomiassaf/ngc-webpack#21]
I have an issue with ngc-webpack

I use  [https://github.com/AngularClass/angular-starter](https://github.com/AngularClass/angular-starter) starter that use  ngc-webpack

for example add  dependency to devextreme in one module (for example BarrelModule)

import { DxDataGridModule } from 'devextreme-angular';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

and import DxDataGridModule  int module
in bothe prod and aot build the size of js file is same (4.5 M) 

But if i use AotPlugin  the size of js file is about 2M in aot build

whats the problem?

tanx

**Comment by shlomiassaf** [comment]
2.5 MB difference seems extreme to me, I would like o assume it's not gzipped (at least...)

Do you have a sample I can test? a repository to run AotPlugin against?

Thanks.

**Comment by shlomiassaf** [comment]
I ran a test using the latest **ngc-webpack** 3.1.0 on the latest angular starter repository.

I compared the builds on the starter with the latest version of:

  -  `@ngtools/webpack` **AotPlugin**
  -  **ngc-webpack** 3.0.0
  - **ngc-webpack** 3.1.0

The one with the **ngc-webpack** version 3.1.0 has the **ngc-webpack** loader activated.

![image](https://user-images.githubusercontent.com/5377501/28701398-ad754ece-735e-11e7-98f9-aea31cdc3c1e.png)

As you can see the results from 3.1.0 and `AotPlugin` are identical in terms of bundle size.

The results of 3..0.0 are slightly bigger in the main file but that's not 2.5 MB difference.

Maybe you compared an AotPlugin build that was gzipped with an ngc-webpack that was not?

**Comment by abadakhshan** [comment]
Hello and tankyou for your response

Maybe I'm wrong

please see this repo  [abadakhshan/angular-webpack ](https://github.com/abadakhshan/angular-webpack)

without aot size off app.js is 4.299 M
with npm run build(with AotPlugin):size off app.js is  1.718M

but when i want build with ngc-webpack  i get error ::cannot find module @ Angular/compiler

how can i  use ngc-webpack on this repo?

tanx

**Comment by shlomiassaf** [comment]
Please add a branch where you re-configured the `webpack.config.js` to use `ngc-webpack`

I will see from there
