### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by WiseBird** [shlomiassaf/ngc-webpack#24]
I am playing with AoT and noticed that when using `ngc-webpack` some assets aren't created.
Please check [this commit](https://github.com/WiseBird/Angular-Aot-Example/commit/dddcfeabae139851694ea4c3c8436601de2b3051). After it if I try to build project using `@ngtools/webpack`([config](https://github.com/WiseBird/Angular-Aot-Example/blob/dddcfeabae139851694ea4c3c8436601de2b3051/webpack.config.aot.js)) I am getting:
```
sergey@computer ~/projects/aot_test $ ./node_modules/.bin/webpack --config webpack.config.aot.js 
Hash: 567cbe8c3537b60c2f38
Version: webpack 3.4.1
Time: 4461ms
            Asset       Size  Chunks                    Chunk Names
bundle.avatar.png     2.1 kB          [emitted]         
    0../bundle.js    7.35 kB       0  [emitted]         
      ./bundle.js    1.31 MB       1  [emitted]  [big]  main
       bundle.css  126 bytes       1  [emitted]         main
...
```

and with `ngc-webpack`([config](https://github.com/WiseBird/Angular-Aot-Example/blob/dddcfeabae139851694ea4c3c8436601de2b3051/webpack.config.ngc.js)):
```
sergey@computer ~/projects/aot_test $ ./node_modules/.bin/webpack --config webpack.config.ngc.js 
...
Hash: e959e901fa742c70e34a
Version: webpack 3.4.1
Time: 7831ms
        Asset       Size  Chunks                    Chunk Names
0../bundle.js    5.54 kB       0  [emitted]         
  ./bundle.js    1.31 MB       1  [emitted]  [big]  main
   bundle.css  126 bytes       1  [emitted]         main
...
```

There is no `bundle.avatar.png`(it is referenced in the [template](https://github.com/WiseBird/Angular-Aot-Example/blob/dddcfeabae139851694ea4c3c8436601de2b3051/src/app/lazy/root/lazy.component.html) of lazy loaded component). Do I miss something or this is a bug?

Then I tried to reference more assets in styles in [next commit](https://github.com/WiseBird/Angular-Aot-Example/commit/7b633b4eebcd1d46e14483a2b99487de717bcd5b). And some of them also got ignored:
```
sergey@computer ~/projects/aot_test $ ./node_modules/.bin/webpack --config webpack.config.aot.js 
Hash: fb31cc0ecb14a4e48d3e
Version: webpack 3.4.1
Time: 4691ms
               Asset       Size  Chunks                    Chunk Names
   bundle.avatar.png     2.1 kB          [emitted]         
bundle.check-off.png    2.89 kB          [emitted]         
   bundle.on-off.png    4.62 kB          [emitted]         
 bundle.check-on.png    2.84 kB          [emitted]         
       0../bundle.js     7.4 kB       0  [emitted]         
         ./bundle.js    1.31 MB       1  [emitted]  [big]  main
          bundle.css  182 bytes       1  [emitted]         main
...
```

```
sergey@computer ~/projects/aot_test $ ./node_modules/.bin/webpack --config webpack.config.ngc.js 
...
Hash: 7078a94d761ee584ea50
Version: webpack 3.4.1
Time: 8622ms
              Asset       Size  Chunks                    Chunk Names
bundle.check-on.png    2.84 kB          [emitted]         
      0../bundle.js    5.59 kB       0  [emitted]         
        ./bundle.js    1.31 MB       1  [emitted]  [big]  main
         bundle.css  182 bytes       1  [emitted]         main
...
```

**Comment by shlomiassaf** [comment]
@WiseBird Thank you for the report, this was indeed a bug.

The `resourceOverride` feature was the culprit and now with the AOT cleanup loader, once it is removed (as it's no longer needed), this bug happens.

Anyway, `resourceOverride` has it's issues with assets, removing them along with any other resource so it's better now.
